# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LdFindCodeRefs < Formula
  desc "Job for finding and sending feature flag code references to LaunchDarkly"
  homepage "https://launchdarkly.com"
  version "2.15.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/launchdarkly/ld-find-code-refs/releases/download/v2.15.0/ld-find-code-refs_2.15.0_darwin_arm64.tar.gz"
      sha256 "71afbbea39bf566306f993fc83af466a17300d7b93676d5e43753f6ac8c67ec8"

      def install
        bin.install "ld-find-code-refs"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/launchdarkly/ld-find-code-refs/releases/download/v2.15.0/ld-find-code-refs_2.15.0_darwin_amd64.tar.gz"
      sha256 "21fd1263eae5d05a0a42b82d2af65fac6ee8f4dd23606098c56fa628d72881f6"

      def install
        bin.install "ld-find-code-refs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/launchdarkly/ld-find-code-refs/releases/download/v2.15.0/ld-find-code-refs_2.15.0_linux_arm64.tar.gz"
      sha256 "2405967bab9e813d9baa8ed6bf06a1ea12bc655e1c65944e4ad0a002646961f1"

      def install
        bin.install "ld-find-code-refs"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/launchdarkly/ld-find-code-refs/releases/download/v2.15.0/ld-find-code-refs_2.15.0_linux_amd64.tar.gz"
      sha256 "1713d43b489e2f3a1e4043f1456d5a6bf2dd3a326ed83ef09e7571759688c4d0"

      def install
        bin.install "ld-find-code-refs"
      end
    end
  end
end
