# This file was generated by GoReleaser. DO NOT EDIT.
class LdFindCodeRefs < Formula
  desc "Job for finding and sending feature flag code references to LaunchDarkly"
  homepage "https://launchdarkly.com"
  version "2.0.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/launchdarkly/ld-find-code-refs/releases/download/2.0.0/ld-find-code-refs_2.0.0_darwin_amd64.tar.gz"
    sha256 "fe50c31a5da880a398910909534dc82f7434c925b4050bb35aef0064e9d5b91a"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/launchdarkly/ld-find-code-refs/releases/download/2.0.0/ld-find-code-refs_2.0.0_linux_amd64.tar.gz"
      sha256 "11cfb0eab0148b7117d161272a63568a5559976c7d6b5b6e7946722be6f8d451"
    end
  end

  def install
    bin.install "ld-find-code-refs"
  end
end
