# This file was generated by GoReleaser. DO NOT EDIT.
class LdFindCodeRefs < Formula
  desc "Job for finding and sending feature flag code references to LaunchDarkly"
  homepage "https://launchdarkly.com"
  url "https://github.com/launchdarkly/ld-find-code-refs/releases/download/0.6.0/ld-find-code-refs_0.6.0_darwin_amd64.tar.gz"
  version "0.6.0"
  sha256 "64e401e43461ab6b13ceef673524a9159666ad499812173528ef355c07f518bd"
  
  depends_on "ag"

  def install
    bin.install "ld-find-code-refs"
  end
end
