# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ldcli < Formula
  desc "The official command line interface for managing LaunchDarkly feature flags."
  homepage "https://launchdarkly.com"
  version "1.13.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/launchdarkly/ldcli/releases/download/v1.13.0/ldcli_1.13.0_darwin_amd64.tar.gz"
      sha256 "4584e85b452b8b9eb9ac5506cd7f7737f72bbcfd8dce4140818f0b36b186b1be"

      def install
        bin.install "ldcli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/launchdarkly/ldcli/releases/download/v1.13.0/ldcli_1.13.0_darwin_arm64.tar.gz"
      sha256 "8e398e706e9b3deaaceda326017234c8ce824300462f7ae85d1fde03a45cb594"

      def install
        bin.install "ldcli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/launchdarkly/ldcli/releases/download/v1.13.0/ldcli_1.13.0_linux_amd64.tar.gz"
        sha256 "d27749930a2a669deaa9ef4fa8e0c90af0750b10b123c5cc4301b4857729adc2"

        def install
          bin.install "ldcli"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/launchdarkly/ldcli/releases/download/v1.13.0/ldcli_1.13.0_linux_arm64.tar.gz"
        sha256 "56ac6313af4c0511e9fbc6ce48592d573e76fb120719d27ea1d9b6ce65109b98"

        def install
          bin.install "ldcli"
        end
      end
    end
  end
end
