# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ldcli < Formula
  desc "The official command line interface for managing LaunchDarkly feature flags."
  homepage "https://launchdarkly.com"
  version "0.11.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/launchdarkly/ldcli/releases/download/v0.11.0/ldcli_0.11.0_darwin_amd64.tar.gz"
      sha256 "d65c6708b9b3eaca2a84dd3e5232b034defbe41d2d35f91bcfa1ce14f8dc7c82"

      def install
        bin.install "ldcli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/launchdarkly/ldcli/releases/download/v0.11.0/ldcli_0.11.0_darwin_arm64.tar.gz"
      sha256 "5f80d5a44f7fffd598eece402c2afab980f2f8c7d2832a46c050701693eeff7d"

      def install
        bin.install "ldcli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/launchdarkly/ldcli/releases/download/v0.11.0/ldcli_0.11.0_linux_amd64.tar.gz"
      sha256 "dc7d2c7b5d7d44824bc3929c72586f28edc037a1b754ae35827e8d62bd99bcdd"

      def install
        bin.install "ldcli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/launchdarkly/ldcli/releases/download/v0.11.0/ldcli_0.11.0_linux_arm64.tar.gz"
      sha256 "f1d5a818b15cf4ca97c85886969f55df30a6ca0c534a3490bfaf0a177afbb95b"

      def install
        bin.install "ldcli"
      end
    end
  end
end
