# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ldcli < Formula
  desc "The official command line interface for managing LaunchDarkly feature flags."
  homepage "https://launchdarkly.com"
  version "1.16.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/launchdarkly/ldcli/releases/download/v1.16.0/ldcli_1.16.0_darwin_amd64.tar.gz"
      sha256 "a4245a93bca78efbbe8b8506ba07cecbc3e78d28650ad95c20433b097b089fa8"

      def install
        bin.install "ldcli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/launchdarkly/ldcli/releases/download/v1.16.0/ldcli_1.16.0_darwin_arm64.tar.gz"
      sha256 "e0236a4ecb72603d5f54c8b22616db3fc55078e0874dd8309168621d520c5d71"

      def install
        bin.install "ldcli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/launchdarkly/ldcli/releases/download/v1.16.0/ldcli_1.16.0_linux_amd64.tar.gz"
      sha256 "53f2ed8f2a0a01477c987de2440dd6da04b5bb2488fc6a5c6487847fd2e34aa3"
      def install
        bin.install "ldcli"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/launchdarkly/ldcli/releases/download/v1.16.0/ldcli_1.16.0_linux_arm64.tar.gz"
      sha256 "ff683c298272091268ecfc6daaa34844d606a95b7b6043621a73d9248193edf4"
      def install
        bin.install "ldcli"
      end
    end
  end
end
